baseurl = "http://sergii.me/"
languageCode = "en-US"
title = "SERGII VASHCHYSHCHUK"
# Enable comments by entering your Disqus shortname
disqusShortname = "swniko"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-10057075-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    # Tell me who you are
    author = "Sergii Vashchyshchuk"
    bio = ""
    location = "Sydney, Australia"
    site_description = ""
    copyright  = "Sergii Vashchyshchuk Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar.png"
    logo = "css/images/logo.png"
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
# [[params.menu]]
#     before = true
#     label  = "Home"
#     link   = "/"

# [[params.menu]]
#     before = false
#     label  = "Tags"
#     link   = "tags/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/swniko"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "sniko"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "swniko"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = false
    tags = true
    tag_cloud = false
